// Dental services catalog — configuration-driven, easy to edit
export const SERVICES = [
  {
    id: 'consultation',
    name: 'Dental Consultation',
    shortName: 'Consultation',
    description: 'Comprehensive oral health check-up with expert dental advice and treatment planning.',
    icon: '🦷',
    price: '₹200 - ₹500',
    duration: '30 min',
    category: 'general',
    popular: true,
  },
  {
    id: 'cleaning',
    name: 'Teeth Cleaning & Polishing',
    shortName: 'Cleaning',
    description: 'Professional scaling, polishing, and plaque removal for a brighter, healthier smile.',
    icon: '✨',
    price: '₹500 - ₹1,500',
    duration: '45 min',
    category: 'preventive',
    popular: true,
  },
  {
    id: 'rct',
    name: 'Root Canal Treatment',
    shortName: 'RCT',
    description: 'Advanced endodontic treatment to save infected teeth and eliminate pain permanently.',
    icon: '🔬',
    price: '₹3,000 - ₹8,000',
    duration: '60–90 min',
    category: 'restorative',
    popular: true,
  },
  {
    id: 'whitening',
    name: 'Teeth Whitening',
    shortName: 'Whitening',
    description: 'Professional teeth whitening for a radiant, confident smile. Safe and effective.',
    icon: '💎',
    price: '₹3,000 - ₹10,000',
    duration: '60 min',
    category: 'cosmetic',
    popular: false,
  },
  {
    id: 'implants',
    name: 'Dental Implants',
    shortName: 'Implants',
    description: 'Permanent titanium implants — the gold standard for replacing missing teeth.',
    icon: '🏗️',
    price: '₹15,000 - ₹40,000',
    duration: 'Multiple visits',
    category: 'restorative',
    popular: false,
  },
  {
    id: 'crowns',
    name: 'Dental Crowns & Bridges',
    shortName: 'Crowns',
    description: 'Custom-crafted crowns and bridges to restore damaged or missing teeth perfectly.',
    icon: '👑',
    price: '₹2,000 - ₹15,000',
    duration: '2–3 visits',
    category: 'restorative',
    popular: false,
  },
  {
    id: 'braces',
    name: 'Braces & Aligners',
    shortName: 'Braces',
    description: 'Orthodontic treatment with traditional braces or clear aligners for perfect alignment.',
    icon: '😁',
    price: '₹25,000 - ₹80,000',
    duration: '12–24 months',
    category: 'orthodontic',
    popular: true,
  },
  {
    id: 'extraction',
    name: 'Tooth Extraction',
    shortName: 'Extraction',
    description: 'Safe and painless tooth removal including wisdom teeth extraction by experts.',
    icon: '🩺',
    price: '₹500 - ₹3,000',
    duration: '30–60 min',
    category: 'surgical',
    popular: false,
  },
  {
    id: 'kids',
    name: 'Kids Dentistry',
    shortName: 'Kids',
    description: 'Gentle, child-friendly dental care including fluoride treatments and sealants.',
    icon: '👶',
    price: '₹300 - ₹2,000',
    duration: '30 min',
    category: 'pediatric',
    popular: false,
  },
  {
    id: 'gum',
    name: 'Gum Treatment',
    shortName: 'Gum Care',
    description: 'Advanced periodontal care for bleeding gums, infection, and gum disease management.',
    icon: '🫧',
    price: '₹1,000 - ₹5,000',
    duration: '30–60 min',
    category: 'preventive',
    popular: false,
  },
  {
    id: 'dentures',
    name: 'Dentures',
    shortName: 'Dentures',
    description: 'Comfortable, natural-looking removable dentures for partial or complete tooth replacement.',
    icon: '🦴',
    price: '₹5,000 - ₹25,000',
    duration: '3–4 visits',
    category: 'restorative',
    popular: false,
  },
  {
    id: 'xray',
    name: 'Dental X-Ray & Diagnosis',
    shortName: 'X-Ray',
    description: 'Digital dental X-rays for accurate diagnosis and treatment planning.',
    icon: '📋',
    price: '₹200 - ₹800',
    duration: '15 min',
    category: 'diagnostic',
    popular: false,
  },
];

export const SERVICE_CATEGORIES = [
  { id: 'all', name: 'All Services' },
  { id: 'general', name: 'General' },
  { id: 'preventive', name: 'Preventive' },
  { id: 'restorative', name: 'Restorative' },
  { id: 'cosmetic', name: 'Cosmetic' },
  { id: 'orthodontic', name: 'Orthodontic' },
  { id: 'surgical', name: 'Surgical' },
  { id: 'pediatric', name: 'Pediatric' },
  { id: 'diagnostic', name: 'Diagnostic' },
];

export const TIME_SLOTS = [
  '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
  '06:00 PM', '06:30 PM', '07:00 PM', '07:30 PM',
  '08:00 PM', '08:30 PM',
];
