// Multi-specialty services catalog — configuration-driven, easy to edit
export const SERVICES = [
  // ───────────────────────────────────────────────
  // DENTAL (general)
  // ───────────────────────────────────────────────
  {
    id: 'consultation',
    name: 'General Dental Consultation',
    shortName: 'Consultation',
    description: 'Specialist-led consultation with personalized treatment planning and X-ray assessment.',
    icon: 'Stethoscope',
    duration: '30 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'cleaning',
    name: 'Teeth Cleaning & Polishing',
    shortName: 'Cleaning',
    description: 'Professional scaling, polishing, and plaque removal for a brighter, healthier smile.',
    icon: 'Sparkles',
    duration: '45 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'rct',
    name: 'Root Canal Treatment (RCT)',
    shortName: 'RCT',
    description: 'Rotary single-sitting endodontic treatment to save infected teeth and eliminate pain permanently.',
    icon: 'Microscope',
    duration: '60–90 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'extraction',
    name: 'Tooth Extraction',
    shortName: 'Extraction',
    description: 'Safe and painless tooth removal by experts — with minimal discomfort protocols.',
    icon: 'Tooth',
    duration: '30–60 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'kids',
    name: 'Kids Dentistry (Pedodontics)',
    shortName: 'Kids',
    description: 'Gentle child-friendly dental care — fluoride, sealants, and early orthodontic screening.',
    icon: 'Baby',
    duration: '30 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'gum',
    name: 'Gum & Bone Treatment',
    shortName: 'Gum Care',
    description: 'Periodontal care for bleeding gums, infection, and advanced gum disease management.',
    icon: 'Wind',
    duration: '30–60 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'xray',
    name: 'Dental X-Ray & Diagnostics',
    shortName: 'X-Ray',
    description: 'Digital radiography for accurate diagnosis and treatment planning. On-site pharmacy & lab.',
    icon: 'Clipboard',
    duration: '15 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'braces',
    name: 'Braces & Clear Aligners',
    shortName: 'Orthodontics',
    description: 'Orthodontic treatment with traditional braces or certified Invisalign-style clear aligners.',
    icon: 'Smile',
    duration: '12–24 months',
    category: 'dental',
    popular: true,
  },

  // ───────────────────────────────────────────────
  // ORAL & MAXILLOFACIAL SURGERY
  // ───────────────────────────────────────────────
  {
    id: 'wisdom-tooth',
    name: 'Wisdom Tooth Surgery',
    shortName: 'Wisdom Tooth',
    description: 'Impacted third molar removal under local anaesthesia with advanced surgical protocols.',
    icon: 'Hammer',
    duration: '45–90 min',
    category: 'maxillofacial',
    popular: true,
  },
  {
    id: 'cysts-tumors',
    name: 'Cyst & Tumor Removal',
    shortName: 'Cyst & Tumor',
    description: 'Surgical removal of jaw cysts, benign tumors, and pathologies with biopsy support.',
    icon: 'Beaker',
    duration: 'Case based',
    category: 'maxillofacial',
    popular: false,
  },
  {
    id: 'facial-injuries',
    name: 'Facial Injuries & Trauma',
    shortName: 'Facial Trauma',
    description: 'Maxillofacial trauma management — fractures, lacerations, and reconstructive bone work.',
    icon: 'Bandage',
    duration: 'Multi-session',
    category: 'maxillofacial',
    popular: false,
  },
  {
    id: 'facial-plastic',
    name: 'Facial Plastic Surgery',
    shortName: 'Facial Plastic',
    description: 'Scar revision, reconstructive procedures, and aesthetic corrections by senior plastic surgeons.',
    icon: 'Scissors',
    duration: 'Case based',
    category: 'maxillofacial',
    popular: false,
  },
  {
    id: 'orofacial-cleft',
    name: 'Orofacial Cleft Surgery',
    shortName: 'Cleft',
    description: 'Cleft lip & palate correction for children and adults with staged rehabilitation support.',
    icon: 'Baby',
    duration: 'Multi-stage',
    category: 'maxillofacial',
    popular: false,
  },
  {
    id: 'orthognathic',
    name: 'Orthognathic & Jaw Surgery',
    shortName: 'Jaw Surgery',
    description: 'Corrective jaw surgery for bite, breathing, and facial-profile alignment.',
    icon: 'Skeleton',
    duration: 'Multi-visit',
    category: 'maxillofacial',
    popular: false,
  },

  // ───────────────────────────────────────────────
  // DENTAL IMPLANTS
  // ───────────────────────────────────────────────
  {
    id: 'single-implant',
    name: 'Single Tooth Implant',
    shortName: 'Single Implant',
    description: 'Permanent titanium implant with custom crown — the gold standard for one missing tooth.',
    icon: 'Hammer',
    duration: '2–3 visits',
    category: 'implants',
    popular: true,
  },
  {
    id: 'multiple-implant',
    name: 'Multiple Tooth Implants',
    shortName: 'Multiple Implants',
    description: 'Implant-supported bridges for multiple missing teeth — stable, natural, and long-lasting.',
    icon: 'Building',
    duration: 'Multi-visit',
    category: 'implants',
    popular: true,
  },
  {
    id: 'full-mouth-implant',
    name: 'Full Mouth Rehabilitation',
    shortName: 'Full Mouth',
    description: 'All-on-4 / All-on-6 full-arch implant rehabilitation for complete oral reconstruction.',
    icon: 'Crown',
    duration: '3–6 months',
    category: 'implants',
    popular: true,
  },
  {
    id: 'advanced-implantology',
    name: 'Advanced Implantology',
    shortName: 'Advanced',
    description: 'Immediate loading, zygomatic implants, and bone grafting for complex implant cases.',
    icon: 'Dna',
    duration: 'Staged',
    category: 'implants',
    popular: false,
  },

  // ───────────────────────────────────────────────
  // COSMETIC DENTISTRY
  // ───────────────────────────────────────────────
  {
    id: 'whitening',
    name: 'Teeth Whitening',
    shortName: 'Whitening',
    description: 'Professional chairside whitening for a radiant, confident smile — safe and effective.',
    icon: 'Diamond',
    duration: '60 min',
    category: 'cosmetic',
    popular: true,
  },
  {
    id: 'tooth-jewelry',
    name: 'Tooth Jewellery',
    shortName: 'Jewellery',
    description: 'Dental jewels bonded to your teeth — a painless aesthetic accent that reflects light.',
    icon: 'Gem',
    duration: '20 min',
    category: 'cosmetic',
    popular: false,
  },
  {
    id: 'gummy-smile',
    name: 'Gummy Smile Correction',
    shortName: 'Gummy Smile',
    description: 'Laser or surgical gum contouring to reveal a more balanced, proportionate smile.',
    icon: 'Smile',
    duration: '45 min',
    category: 'cosmetic',
    popular: false,
  },
  {
    id: 'veneers',
    name: 'Laminates & Veneers',
    shortName: 'Veneers',
    description: 'Porcelain veneers and laminates for smile designing — chips, spacing, and colour.',
    icon: 'Mirror',
    duration: '2–3 visits',
    category: 'cosmetic',
    popular: true,
  },
  {
    id: 'crowns',
    name: 'Crowns & Bridges',
    shortName: 'Crowns',
    description: 'Zirconia, E-max, and ceramic crowns crafted to restore damaged or missing teeth.',
    icon: 'Crown',
    duration: '2–3 visits',
    category: 'cosmetic',
    popular: false,
  },
  {
    id: 'smile-design',
    name: 'Digital Smile Designing',
    shortName: 'Smile Design',
    description: 'Digitally planned smile makeover combining veneers, whitening, and gum contouring.',
    icon: 'Palette',
    duration: 'Multi-visit',
    category: 'cosmetic',
    popular: true,
  },

  // ───────────────────────────────────────────────
  // HAIR (TRICHOLOGY)
  // ───────────────────────────────────────────────
  {
    id: 'hair-consultation',
    name: 'Trichology Consultation',
    shortName: 'Hair Consult',
    description: 'Scalp analysis, diagnostic workup, and personalised restoration plan by hair specialists.',
    icon: 'Stethoscope',
    duration: '30 min',
    category: 'hair',
    popular: true,
  },
  {
    id: 'alopecia',
    name: 'Alopecia Areata Treatment',
    shortName: 'Alopecia',
    description: 'Medical management for patchy hair loss with intralesional steroids and topicals.',
    icon: 'Bottle',
    duration: 'Session based',
    category: 'hair',
    popular: false,
  },
  {
    id: 'hair-transplant',
    name: 'Hair Transplant (FUE/FUT)',
    shortName: 'Hair Tx',
    description: 'Permanent hair restoration by UK-certified transplant surgeon using advanced grafting.',
    icon: 'Leaf',
    duration: '6–8 hr session',
    category: 'hair',
    popular: true,
  },
  {
    id: 'prp-hair',
    name: 'PRP / GFC Hair Therapy',
    shortName: 'PRP',
    description: 'Platelet-rich plasma & growth-factor concentrate sessions to improve scalp & density.',
    icon: 'Syringe',
    duration: '45 min',
    category: 'hair',
    popular: true,
  },
  {
    id: 'mesotherapy',
    name: 'Hair Mesotherapy',
    shortName: 'Mesotherapy',
    description: 'Micro-injection of vitamins, peptides, and nutrients directly into the scalp.',
    icon: 'Beaker',
    duration: '30 min',
    category: 'hair',
    popular: false,
  },
  {
    id: 'laser-hair-reduction',
    name: 'Laser Hair Reduction',
    shortName: 'Laser Hair',
    description: 'Long-term hair reduction with skin-type based laser protocols, face & full body.',
    icon: 'Sparkles',
    duration: '20–60 min',
    category: 'hair',
    popular: true,
  },

  // ───────────────────────────────────────────────
  // COSMETOLOGY / AESTHETIC SKIN
  // ───────────────────────────────────────────────
  {
    id: 'skin-consultation',
    name: 'Aesthetic Skin Consultation',
    shortName: 'Skin Consult',
    description: 'Doctor-led skin assessment with personalised protocol planning and skincare advice.',
    icon: 'Radar',
    duration: '30 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'chemical-peel',
    name: 'Medical Chemical Peels',
    shortName: 'Peels',
    description: 'Clinic-grade peels for acne marks, dullness, and uneven tone under dermatologist supervision.',
    icon: 'Bottle',
    duration: '30 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'microdermabrasion',
    name: 'Microdermabrasion',
    shortName: 'Microderm',
    description: 'Gentle mechanical exfoliation to refresh skin texture and open congested pores.',
    icon: 'Hand',
    duration: '30 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'hydrafacial',
    name: 'Hydrafacial',
    shortName: 'Hydrafacial',
    description: 'Signature multi-step hydration facial for instant glow and deep cleansing.',
    icon: 'Drop',
    duration: '45 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'prp-skin',
    name: 'PRP / GFC for Skin',
    shortName: 'PRP Skin',
    description: 'Platelet-rich plasma for acne scars, skin texture, and facial rejuvenation.',
    icon: 'Syringe',
    duration: '45 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'carboxytherapy',
    name: 'Carboxytherapy',
    shortName: 'Carboxy',
    description: 'Medical CO₂ therapy for dark circles, stretch marks, and localised fat reduction.',
    icon: 'Wind',
    duration: '30 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'skin-laser',
    name: 'Laser Skin Rejuvenation',
    shortName: 'Skin Laser',
    description: 'Lasers for texture, pigmentation, and rejuvenation — tailored to your skin profile.',
    icon: 'Leaf',
    duration: '30–60 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'botox',
    name: 'Botox (Anti-Wrinkle)',
    shortName: 'Botox',
    description: 'FDA-approved neuromodulator for forehead lines, crow\'s feet, and facial slimming.',
    icon: 'Star',
    duration: '20 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'fillers',
    name: 'Dermal Fillers',
    shortName: 'Fillers',
    description: 'Hyaluronic acid fillers for lips, cheeks, jawline definition, and under-eye correction.',
    icon: 'Lips',
    duration: '30 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'threads',
    name: 'Thread Lift',
    shortName: 'Threads',
    description: 'PDO/PCL threads for non-surgical face lifting, contouring, and skin tightening.',
    icon: 'Needle',
    duration: '45 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'skin-tag',
    name: 'Skin Tag & Mole Removal',
    shortName: 'Tag & Mole',
    description: 'Radiofrequency and laser removal of skin tags, moles, and warts — minimal scar.',
    icon: 'XCircle',
    duration: '15–30 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'scar-pigmentation',
    name: 'Scar & Pigmentation Care',
    shortName: 'Pigment Care',
    description: 'Structured plans for scars and pigmentation combining procedures and home-care guidance.',
    icon: 'Mirror',
    duration: 'Consultation based',
    category: 'skin',
    popular: false,
  },
];

export const SERVICE_CATEGORIES = [
  { id: 'all', name: 'All Services' },
  { id: 'dental', name: 'Dental' },
  { id: 'maxillofacial', name: 'Oral & Maxillofacial Surgery' },
  { id: 'hair', name: 'Hair / Trichology' },
  { id: 'skin', name: 'Cosmetology / Skin' },
  { id: 'implants', name: 'Dental Implants' },
  { id: 'cosmetic', name: 'Cosmetic Dentistry' },
];

// Mon–Sat 10:00 AM to 7:30 PM (Sundays closed)
export const TIME_SLOTS = [
  '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
  '06:00 PM', '06:30 PM', '07:00 PM', '07:30 PM',
];
