// Multi-specialty services catalog — configuration-driven, easy to edit
export const SERVICES = [
  {
    id: 'consultation',
    name: 'General Consultation',
    shortName: 'Consultation',
    description: 'Specialist-led consultation for dental, hair, or skin concerns with personalized treatment planning.',
    icon: '🩺',
    price: '₹200 - ₹500',
    duration: '30 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'cleaning',
    name: 'Teeth Cleaning & Polishing',
    shortName: 'Cleaning',
    description: 'Professional scaling, polishing, and plaque removal for a brighter, healthier smile.',
    icon: '✨',
    price: '₹500 - ₹1,500',
    duration: '45 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'rct',
    name: 'Root Canal Treatment',
    shortName: 'RCT',
    description: 'Advanced endodontic treatment to save infected teeth and eliminate pain permanently.',
    icon: '🔬',
    price: '₹3,000 - ₹8,000',
    duration: '60–90 min',
    category: 'dental',
    popular: true,
  },
  {
    id: 'whitening',
    name: 'Teeth Whitening',
    shortName: 'Whitening',
    description: 'Professional teeth whitening for a radiant, confident smile. Safe and effective.',
    icon: '💎',
    price: '₹3,000 - ₹10,000',
    duration: '60 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'implants',
    name: 'Dental Implants',
    shortName: 'Implants',
    description: 'Permanent titanium implants — the gold standard for replacing missing teeth.',
    icon: '🏗️',
    price: '₹15,000 - ₹40,000',
    duration: 'Multiple visits',
    category: 'dental',
    popular: true,
  },
  {
    id: 'crowns',
    name: 'Dental Crowns & Bridges',
    shortName: 'Crowns',
    description: 'Custom-crafted crowns and bridges to restore damaged or missing teeth perfectly.',
    icon: '👑',
    price: '₹2,000 - ₹15,000',
    duration: '2–3 visits',
    category: 'dental',
    popular: false,
  },
  {
    id: 'braces',
    name: 'Braces & Aligners',
    shortName: 'Braces',
    description: 'Orthodontic treatment with traditional braces or clear aligners for perfect alignment.',
    icon: '😁',
    price: '₹25,000 - ₹80,000',
    duration: '12–24 months',
    category: 'dental',
    popular: true,
  },
  {
    id: 'extraction',
    name: 'Tooth Extraction',
    shortName: 'Extraction',
    description: 'Safe and painless tooth removal including wisdom teeth extraction by experts.',
    icon: '🩺',
    price: '₹500 - ₹3,000',
    duration: '30–60 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'kids',
    name: 'Kids Dentistry',
    shortName: 'Kids',
    description: 'Gentle, child-friendly dental care including fluoride treatments and sealants.',
    icon: '👶',
    price: '₹300 - ₹2,000',
    duration: '30 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'gum',
    name: 'Gum Treatment',
    shortName: 'Gum Care',
    description: 'Advanced periodontal care for bleeding gums, infection, and gum disease management.',
    icon: '🫧',
    price: '₹1,000 - ₹5,000',
    duration: '30–60 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'dentures',
    name: 'Dentures',
    shortName: 'Dentures',
    description: 'Comfortable, natural-looking removable dentures for partial or complete tooth replacement.',
    icon: '🦴',
    price: '₹5,000 - ₹25,000',
    duration: '3–4 visits',
    category: 'dental',
    popular: false,
  },
  {
    id: 'xray',
    name: 'Dental X-Ray & Diagnosis',
    shortName: 'X-Ray',
    description: 'Digital dental X-rays for accurate diagnosis and treatment planning.',
    icon: '📋',
    price: '₹200 - ₹800',
    duration: '15 min',
    category: 'dental',
    popular: false,
  },
  {
    id: 'hair-transplant',
    name: 'Hair Transplant (FUE/FUT)',
    shortName: 'Hair Tx',
    description: 'Medical hair restoration using modern grafting techniques with detailed post-op monitoring.',
    icon: '🧬',
    price: '₹45,000 - ₹1,80,000',
    duration: 'Session-based',
    category: 'hair',
    popular: true,
  },
  {
    id: 'prp-hair',
    name: 'PRP Hair Therapy',
    shortName: 'PRP',
    description: 'Platelet-rich plasma sessions to support scalp health and improve hair density.',
    icon: '💉',
    price: '₹4,000 - ₹12,000',
    duration: '45 min',
    category: 'hair',
    popular: false,
  },
  {
    id: 'laser-hair-reduction',
    name: 'Laser Hair Reduction',
    shortName: 'Laser Hair',
    description: 'Targeted laser treatment for long-term hair reduction with skin-type based protocols.',
    icon: '✨',
    price: '₹2,500 onwards / session',
    duration: '20–60 min',
    category: 'hair',
    popular: true,
  },
  {
    id: 'skin-laser',
    name: 'Laser Skin Rejuvenation',
    shortName: 'Skin Laser',
    description: 'Laser protocols for texture, pigmentation, and rejuvenation customized to your skin profile.',
    icon: '🌿',
    price: '₹3,000 onwards / session',
    duration: '30–60 min',
    category: 'skin',
    popular: true,
  },
  {
    id: 'chemical-peel',
    name: 'Medical Chemical Peel',
    shortName: 'Peel',
    description: 'Clinic-grade peels for acne marks, dullness, and uneven tone under dermatologist supervision.',
    icon: '🧴',
    price: '₹1,500 - ₹8,000',
    duration: '30 min',
    category: 'skin',
    popular: false,
  },
  {
    id: 'scar-pigmentation',
    name: 'Scar & Pigmentation Care',
    shortName: 'Pigment Care',
    description: 'Structured treatment plans for scars and pigmentation using procedures plus home-care guidance.',
    icon: '🪞',
    price: 'Customized',
    duration: 'Consultation based',
    category: 'skin',
    popular: false,
  },
];

export const SERVICE_CATEGORIES = [
  { id: 'all', name: 'All Services' },
  { id: 'dental', name: 'Precision Dental' },
  { id: 'hair', name: 'Hair Restoration' },
  { id: 'skin', name: 'Aesthetic Skin' },
];

export const TIME_SLOTS = [
  '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
  '06:00 PM', '06:30 PM', '07:00 PM', '07:30 PM',
  '08:00 PM', '08:30 PM',
];
